name: Build Static Site for Development

on:
  push:
    branches:
      - jason-github-pages  # Only trigger on your development branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: jason-github-pages  # Explicitly checkout your branch

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build static site
        run: bun run build:static

      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la out/
          echo "Build verification complete"

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Remove existing files except .git
          git rm -r --cached .
          
          # Copy out directory contents to root
          cp -r out/* .
          
          # Add all files
          git add .
          
          # Commit and push
          git commit -m "chore: deploy static site to root [skip ci]"
          git push origin jason-github-pages --force
